name: Gatsby Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: sudo apt-get install tree
      - run: npm install
      - run: tree -I node_modules
      # This triggers `gatsby build` script in "package.json"
      - run: npm build
      - run: tree -I node_modules
