name: Gatsby Publish

push:
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      # This triggers `gatsby build` script in "package.json"
      - run: npm run-script deploy
